### ISSUE TITLE
Version confusion

### ISSUE THREAD

**Issue by citrusella** [markusressel/KutePreferences#41]
I wanted to mess around with this library but ran into roadblocks due to the documentation. The readme suggests version `v3.0.0`... except Android Studio insists this version of the library does not exist. But using version v2.0.0 requires a different process as far as I can tell (and the old version of the readme reflects this, though I haven't tried its instructions yet). I had been trying to get the ViewModel working but was failing at every turn and it more or less took me building the project for a different reason to figure it out because I figured the readme couldn't possibly be referring to a nonexistent version of the library. Figured it was worth making an issue about.

**Comment by markusressel** [comment]
Hey @citrusella! :nerd_face: 
Thx for opening an issue! :rocket: 

Its true, I have not yet released version 3.0.0 . While I have invested lots of time into it already, I wasn't able to polish everything, so there is no release yet. However, if you are considering the use of this library, I would still encourage you to not use the 2.x.x release but play around with a current master SNAPSHOT version (or a commit from master), since version 3 is a complete rewrite based on compose and a completely new architecture under the hood. There might be breaking changes before 3.0.0 is finally released though.

To see how I use KutePreferences myself, have a look at the preferences related classes in MkDocsEditor-Android:
https://github.com/MkDocsEditor/MkDocsEditor-Android/blob/master/app/src/main/java/de/markusressel/mkdocseditor/feature/preferences/ui/PreferencesViewModel.kt

Actually this is slightly out of date, a better source would be the example app within this repo:

https://github.com/markusressel/KutePreferences/blob/master/app/src/main/java/de/markusressel/kutepreferences/app/ui/MainActivity.kt

https://github.com/markusressel/KutePreferences/blob/master/app/src/main/java/de/markusressel/kutepreferences/app/ui/MainViewModel.kt

I think the current state is pretty usable already (I use it in my apps for everything settings related), but the API design is not stable.

Thx for checking out the project!
If you have any further feedback, please let me know! :heart:

**Comment by markusressel** [comment]
@citrusella Out if curiosity, did you get to play around with the master branch? Any constructive Feedback would be very much appreciated ❤️

**Comment by citrusella** [comment]
I never did properly get to play around with it, no. (I ended up going a different way for what I was using to do the preferences is all.) Sorry I don't have feedback!

**Comment by markusressel** [comment]
Thx for taking the time to respond!
